services:
  ngrok:
    image: ngrok/ngrok
    env_file: secret.secret
    networks:
      - example_net
    command: ['http', 'pyserv:8000']
    ports:
      - 4040:4040
  pyserv:
    networks:
      - example_net
    build: repo_imgs

volumes:
  my_vol:
networks:
  example_net:
